# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11EtjS0txLs16qsRyN8kZnLXUG7FsiC6b
"""

from sklearn.datasets import fetch_20newsgroups

cats = ['rec.autos', 'comp.graphics']

newsgroups_train = fetch_20newsgroups(subset='train', categories=cats)

print(f"Training data size: {len(newsgroups_train.data)}")
print(f"Categories: {newsgroups_train.target_names}")
print(f"First 5 samples (first 200 characters each):")
for i in range(5):
    print(f"Sample {i+1}: {newsgroups_train.data[i][:200]}...")

print(f"Labels for the first 5 samples: {newsgroups_train.target[:5]}")

print(f"Features (first 5 sample texts):")
for i in range(5):
    print(f"Sample {i+1}: {newsgroups_train.data[i][:200]}...")

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(stop_words='english', ngram_range=(1, 2), min_df=2, max_df=0.9)

X_train_tfidf = tfidf_vectorizer.fit_transform(newsgroups_train.data)

print(f"Shape of TF-IDF matrix: {X_train_tfidf.shape}")
print(f"Number of features (terms): {X_train_tfidf.shape[1]}")

!pip install gensim

import gensim.downloader as api
import numpy as np
word2vec_model = api.load('word2vec-google-news-300')

def get_word2vec_embedding(doc, model):
    words = doc.split()
    word_vectors = []

    for word in words:
        if word in model:
            word_vectors.append(model[word])

    if word_vectors:
        return np.mean(word_vectors, axis=0)
    else:
        return np.zeros(model.vector_size)
word2vec_train_embeddings = []

for doc in newsgroups_train.data:
    try:
        embedding = get_word2vec_embedding(doc, word2vec_model)
        word2vec_train_embeddings.append(embedding)
    except Exception as e:
        print(f"Error processing document: {e}")

        word2vec_train_embeddings.append(np.zeros(word2vec_model.vector_size))

word2vec_train_embeddings = np.array(word2vec_train_embeddings)

print(f"Shape of Word2Vec embeddings: {word2vec_train_embeddings.shape}")

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# Spliting
X_train_split, X_val_split, y_train_split, y_val_split = train_test_split(
    word2vec_train_embeddings, newsgroups_train.target, test_size=0.2, random_state=42
)

# Training
clf_word2vec = LogisticRegression(max_iter=2000)
clf_word2vec.fit(X_train_split, y_train_split)

y_val_pred_word2vec = clf_word2vec.predict(X_val_split)
print("Word2Vec - Validation Performance:")
print(classification_report(y_val_split, y_val_pred_word2vec, target_names=newsgroups_train.target_names))

X_train_split_tfidf, X_val_split_tfidf, y_train_split_tfidf, y_val_split_tfidf = train_test_split(
    X_train_tfidf, newsgroups_train.target, test_size=0.2, random_state=42
)

clf_tfidf = LogisticRegression(max_iter=2000)
clf_tfidf.fit(X_train_split_tfidf, y_train_split_tfidf)

# Evaluation
y_val_pred_tfidf = clf_tfidf.predict(X_val_split_tfidf)
print("TF-IDF - Validation Performance:")
print(classification_report(y_val_split_tfidf, y_val_pred_tfidf, target_names=newsgroups_train.target_names))

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

X_train_split, X_val_split, y_train_split, y_val_split = train_test_split(
    word2vec_train_embeddings, newsgroups_train.target, test_size=0.2, random_state=42
)

# Training the model
clf_word2vec = LogisticRegression(max_iter=2000)
clf_word2vec.fit(X_train_split, y_train_split)

# and Evaluaton
y_val_pred_word2vec = clf_word2vec.predict(X_val_split)

print("Word2Vec - Validation Performance:")
print(classification_report(y_val_split, y_val_pred_word2vec, target_names=newsgroups_train.target_names))

import tarfile
import os

tar_file_path = '/content/aclImdb_v1.tar.gz'

extract_dir = '/content/aclImdb'

with tarfile.open(tar_file_path, 'r') as tar:
    tar.extractall(path=extract_dir)

print("Extraction completed!")

os.listdir(extract_dir)

extract_dir = '/content/aclImdb/aclImdb'
train_dir = os.path.join(extract_dir, 'train')
test_dir = os.path.join(extract_dir, 'test')

def load_imdb_data_full(data_dir):
    texts = []
    labels = []

    for label_type in ['pos', 'neg']:
        folder_path = os.path.join(data_dir, label_type)
        files = [f for f in os.listdir(folder_path) if f.endswith('.txt')]

        for fname in files:
            with open(os.path.join(folder_path, fname), encoding='utf-8') as f:
                texts.append(f.read())
                labels.append(1 if label_type == 'pos' else 0)
    return texts, labels

# Load full training data
train_texts, train_labels = load_imdb_data_full(train_dir)

test_texts, test_labels = load_imdb_data_full(test_dir)

print(f"Training samples: {len(train_texts)}")
print(f"Test samples: {len(test_texts)}")
print(f"First training review label: {train_labels[0]}")
print(f"First training review text:\n{train_texts[0][:500]}")

from sklearn.feature_extraction.text import TfidfVectorizer


tfidf_vectorizer = TfidfVectorizer(stop_words='english', ngram_range=(1,2), min_df=5, max_df=0.9)

# transformtrain and test sets
X_train_tfidf = tfidf_vectorizer.fit_transform(train_texts)
X_test_tfidf = tfidf_vectorizer.transform(test_texts)

print(f"TF-IDF training matrix shape: {X_train_tfidf.shape}")
print(f"TF-IDF test matrix shape: {X_test_tfidf.shape}")

word2vec_model = api.load('word2vec-google-news-300')

def get_word2vec_embedding(doc, model):
    words = doc.split()
    word_vectors = [model[word] for word in words if word in model]
    if word_vectors:
        return np.mean(word_vectors, axis=0)
    else:
        return np.zeros(model.vector_size)

# Transform texts
X_train_w2v = np.array([get_word2vec_embedding(doc, word2vec_model) for doc in train_texts])
X_test_w2v = np.array([get_word2vec_embedding(doc, word2vec_model) for doc in test_texts])

print(f"Word2Vec training matrix shape: {X_train_w2v.shape}")

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

# Train Logistic Regression
clf_tfidf = LogisticRegression(max_iter=2000)
clf_tfidf.fit(X_train_tfidf, train_labels)

# Predict on test set
y_pred = clf_tfidf.predict(X_test_tfidf)

# Evaluate
print(classification_report(test_labels, y_pred))
clf_lr_w2v = LogisticRegression(max_iter=2000)
clf_lr_w2v.fit(X_train_w2v, train_labels)
y_pred_lr_w2v = clf_lr_w2v.predict(X_test_w2v)

# Print performance
print("(Word2Vec):")
print(classification_report(test_labels, y_pred_lr_w2v, target_names=['0', '1']))

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
def plot_confusion(y_true, y_pred, classes, title):
    cm = confusion_matrix(y_true, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=classes)
    disp.plot(cmap=plt.cm.Blues, values_format='d')
    plt.title(title)
    plt.show()

import numpy as np
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
import gensim.downloader as api
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

categories = ['rec.autos', 'comp.graphics']
newsgroups_train = fetch_20newsgroups(subset='train', categories=categories, shuffle=True, random_state=42)
newsgroups_test  = fetch_20newsgroups(subset='test',  categories=categories, shuffle=True, random_state=42)

# TF-IDF Embedding
tfidf_vectorizer = TfidfVectorizer(stop_words='english', ngram_range=(1,2), min_df=2, max_df=0.9)
X_train_tfidf = tfidf_vectorizer.fit_transform(newsgroups_train.data)
X_test_tfidf  = tfidf_vectorizer.transform(newsgroups_test.data)

# Word2Vec Embedding
word2vec_model = api.load('word2vec-google-news-300')

def get_word2vec_embedding(doc, model):
    words = doc.split()
    vectors = [model[word] for word in words if word in model]
    if vectors:
        return np.mean(vectors, axis=0)
    else:
        return np.zeros(model.vector_size)

X_train_w2v = np.array([get_word2vec_embedding(doc, word2vec_model) for doc in newsgroups_train.data])
X_test_w2v  = np.array([get_word2vec_embedding(doc, word2vec_model) for doc in newsgroups_test.data])

#  Logistic Regression
clf_lr_tfidf = LogisticRegression(max_iter=2000)
clf_lr_tfidf.fit(X_train_tfidf, newsgroups_train.target)
y_pred_lr_tfidf = clf_lr_tfidf.predict(X_test_tfidf)

clf_lr_w2v = LogisticRegression(max_iter=2000)
clf_lr_w2v.fit(X_train_w2v, newsgroups_train.target)
y_pred_lr_w2v = clf_lr_w2v.predict(X_test_w2v)


def plot_confusion(y_true, y_pred, classes, title):
    cm = confusion_matrix(y_true, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=classes)
    disp.plot(cmap=plt.cm.Blues, values_format='d')
    plt.title(title)
    plt.show()


classes_20ng = newsgroups_train.target_names
plot_confusion(newsgroups_test.target, y_pred_lr_tfidf, classes_20ng, "20NG: Logistic Regression (TF-IDF)")
plot_confusion(newsgroups_test.target, y_pred_lr_w2v, classes_20ng, "20NG: Logistic Regression (Word2Vec)")

import os
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import gensim.downloader as api
import matplotlib.pyplot as plt

def load_imdb_data_full(data_dir):
    texts = []
    labels = []
    for label_type in ['pos', 'neg']:
        folder_path = os.path.join(data_dir, label_type)
        files = [f for f in os.listdir(folder_path) if f.endswith('.txt')]
        for fname in files:
            with open(os.path.join(folder_path, fname), encoding='utf-8') as f:
                texts.append(f.read())
                labels.append(1 if label_type == 'pos' else 0)
    return texts, labels
extract_dir = '/content/aclImdb/aclImdb'
train_dir = os.path.join(extract_dir, 'train')
test_dir  = os.path.join(extract_dir, 'test')

train_texts, train_labels = load_imdb_data_full(train_dir)
test_texts, test_labels   = load_imdb_data_full(test_dir)

print(f"Training samples: {len(train_texts)}, Test samples: {len(test_texts)}")

#TF-IDF Embedding
tfidf_vectorizer = TfidfVectorizer(stop_words='english', ngram_range=(1,2), min_df=5, max_df=0.9)
X_train_tfidf = tfidf_vectorizer.fit_transform(train_texts)
X_test_tfidf  = tfidf_vectorizer.transform(test_texts)

#Word2Vec Embedding
word2vec_model = api.load('word2vec-google-news-300')

def get_word2vec_embedding(doc, model):
    words = doc.split()
    vectors = [model[word] for word in words if word in model]
    if vectors:
        return np.mean(vectors, axis=0)
    else:
        return np.zeros(model.vector_size)

X_train_w2v = np.array([get_word2vec_embedding(doc, word2vec_model) for doc in train_texts])
X_test_w2v  = np.array([get_word2vec_embedding(doc, word2vec_model) for doc in test_texts])

# Logistic Regression
clf_lr_tfidf = LogisticRegression(max_iter=2000)
clf_lr_tfidf.fit(X_train_tfidf, train_labels)
y_pred_lr_tfidf = clf_lr_tfidf.predict(X_test_tfidf)

clf_lr_w2v = LogisticRegression(max_iter=2000)
clf_lr_w2v.fit(X_train_w2v, train_labels)
y_pred_lr_w2v = clf_lr_w2v.predict(X_test_w2v)


def plot_confusion(y_true, y_pred, classes, title):
    cm = confusion_matrix(y_true, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=classes)
    disp.plot(cmap=plt.cm.Blues, values_format='d')
    plt.title(title)
    plt.show()


classes_imdb = ['Negative', 'Positive']
plot_confusion(test_labels, y_pred_lr_tfidf, classes_imdb, "IMDB: Logistic Regression (TF-IDF)")
plot_confusion(test_labels, y_pred_lr_w2v, classes_imdb, "IMDB: Logistic Regression (Word2Vec)")
